keys:
  - &poli_madoka ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA1uUmneJb2GH7+NsZfjMz2tmoo1aBaXzuuwKLeewCJG poli@madoka
  - &moeka age1gfu88hvhwrxev9ln9r69jkpzpz3vpcr94tjrysq337fu2uvfpe6qzdyp37
creation_rules:
  - path_regex: secrets/common\.yml$
    key_groups:
    - age:
      - *poli_madoka
      - *moeka
  - path_regex: secrets/moeka\.yml$
    key_groups:
    - age:
      - *poli_madoka
      - *moeka
